# Generated by Django 3.2.6 on 2021-08-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('release_date', models.DateField()),
                ('running_time', models.IntegerField()),
                ('actors', models.ManyToManyField(to='actors.Actor')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
